<?php
$wordlist = array(
/* Original wordlist from https://www.plainenglish.co.uk/the-a-z-of-alternative-words.html */
"absence of",
"abundance",
"accede to",
"accelerate",
"accentuate",
"accommodation",
"accompanying",
"accomplish",
"according to our records",
"accordingly",
"acknowledge",
"acquaint yourself with",
"acquiesce",
"acquire",
"additional",
"adjacent",
"adjustment",
"admissible",
"advantageous",
"advise",
"affix",
"afford an opportunity",
"afforded",
"aforesaid",
"aggregate",
"aligned",
"alleviate",
"allocate",
"along the lines of",
"alternative",
"alternatively",
"ameliorate",
"amendment",
"anticipate",
"apparent",
"applicant",
"application",
"appreciable",
"apprise",
"appropriate",
"appropriate to",
"approximately",
"as a consequence of",
"as of the date of",
"as regards",
"ascertain",
"assemble",
"assistance",
"at an early date",
"at its discretion",
"at the moment",
"at the present time",
"attempt",
"attend",
"attributable to",
"authorise",
"authority",
"axiomatic",
"belated",
"beneficial",
"bestow",
"breach",
"by means of",
"calculate",
"cease",
"circumvent",
"clarification",
"combine",
"combined",
"commence",
"communicate",
"competent",
"compile",
"complete",
"completion",
"comply with",
"component",
"comprises",
"compulsory",
"conceal",
"concerning",
"conclusion",
"concur",
"condition",
"consequently",
"considerable",
"constitutes",
"construe",
"consult",
"consumption",
"contemplate",
"contrary to",
"correct",
"correspond",
"costs the sum of",
"counter",
"courteous",
"cumulative",
"currently",
"customary",
"deduct",
"deem to be",
"defer",
"deficiency",
"delete",
"demonstrate",
"denote",
"depict",
"designate",
"desire",
"despatch or dispatch",
"despite the fact that",
"determine",
"detrimental",
"difficulties",
"diminish",
"disburse",
"discharge",
"disclose",
"disconnect",
"discontinue",
"discrete",
"discuss",
"disseminate",
"documentation",
"domiciled in",
"dominant",
"due to the fact that",
"duration",
"during which time",
"dwelling",
"economical",
"eligible",
"elucidate",
"emphasise",
"empower",
"enable",
"enclosed",
"enclosed",
"encounter",
"endeavour",
"enquire",
"enquiry",
"ensure",
"entitlement",
"envisage",
"equivalent",
"erroneous",
"establish",
"evaluate",
"evince",
"ex officio",
"exceptionally",
"excessive",
"exclude",
"excluding",
"exclusively",
"exempt from",
"expedite",
"expeditiously",
"expenditure",
"expire",
"extant",
"extremity",
"fabricate",
"facilitate",
"factor",
"failure to",
"finalise",
"following",
"for the duration of",
"for the purpose of",
"for the reason that",
"formulate",
"forthwith",
"forward",
"frequently",
"furnish",
"further to",
"furthermore",
"generate",
"give consideration to",
"grant",
"henceforth",
"hereby",
"herein",
"hereinafter",
"hereof",
"hereto",
"heretofore",
"hereunder",
"herewith",
"hitherto",
"hold in abeyance",
"hope and trust",
"if and when",
"illustrate",
"immediately",
"implement",
"imply",
"in a number of cases",
"in accordance with",
"in addition",
"in advance",
"in case of",
"in conjunction with",
"in connection with",
"in consequence",
"in excess of",
"in lieu of",
"in order that",
"in receipt of",
"in relation to",
"in respect of",
"in the absence of",
"in the course of",
"in the event",
"in the majority of instances",
"in the near future",
"in the neighbourhood of",
"in view of the fact that",
"inappropriate",
"inception",
"incorporating",
"incur",
"indicate",
"inform",
"initially",
"initiate",
"insert",
"instances",
"intend to",
"intimate",
"irrespective",
"is of the opinion",
"issue",
"it is known that",
"jeopardise",
"large number of",
"locality",
"locate",
"magnitude",
"mandatory",
"manner",
"manufacture",
"marginal",
"material",
"materialise",
"may in the future",
"merchandise",
"mislay",
"modification",
"moreover",
"negligible",
"nevertheless",
"notify",
"notwithstanding",
"numerous",
"objective",
"obligatory",
"obtain",
"occasioned by",
"on behalf of",
"on numerous occasions",
"on request",
"on the grounds that",
"on the occasion that",
"operate",
"optimum",
"option",
"ordinarily",
"otherwise",
"outstanding",
"owing to",
"partially",
"participate",
"particulars",
"per annum",
"perform",
"permissible",
"permit",
"personnel",
"persons",
"peruse",
"place",
"possess",
"possessions",
"practically",
"predominant",
"prescribe",
"preserve",
"previous",
"principal",
"prior to",
"proceed",
"procure",
"profusion of",
"prohibit",
"projected",
"prolonged",
"promptly",
"promulgate",
"proportion",
"provide",
"provided that",
"provisions",
"proximity",
"purchase",
"pursuant to",
"reconsider",
"reduce",
"reduction",
"referred to as",
"refers to",
"regard to",
"regarding",
"regulation",
"reimburse",
"reiterate",
"relating to",
"remain",
"remainder",
"remittance",
"remuneration",
"render",
"report",
"represents",
"request",
"require",
"requirements",
"reside",
"residence",
"restriction",
"retain",
"review",
"revised",
"scrutinise",
"select",
"settle",
"similarly",
"solely",
"specified",
"state",
"statutory",
"subject to",
"submit",
"subsequent",
"subsequently",
"substantial",
"substantially",
"sufficient",
"supplement",
"supplementary",
"supply",
"terminate",
"that being the case",
"the question as to whether",
"thereafter",
"thereby",
"therein",
"thereof",
"thereto",
"thus",
"to date",
"to the extent that",
"transfer",
"transmit",
"ultimately",
"unavailability",
"undernoted",
"undersigned",
"undertake",
"uniform",
"unilateral",
"unoccupied",
"until such time",
"utilisation",
"utilise",
"variation",
"virtually",
"visualise",
"ways and means",
"we have pleasure in",
"whatsoever",
"whensoever",
"whereas",
"whether or not",
"with a view to",
"with effect from",
"with reference to",
"with regard to",
"with respect to",
"with the minimum of delay",
"you are requested",
"your attention is drawn to",
"zone",

// Council words from https://www.theguardian.com/politics/2008/jun/20/localgovernment.localgovernment
"ambassador",
"agencies",
"beacon",
"best practice",
"bottom-up",
"CAAs",
"can do culture",
"capacity",
"cascading",
"cautiously welcome",
"champion",
"citizen empowerment",
"community engagement",
"conditionality",
"consensual",
"contestability",
"core message",
"core value",
"coterminosity",
"coterminous",
"cross-cutting",
"customer",
"democratic mandate",
"democratic legitimacy",
"spending priorities",
"early win",
"empowerment",
"engagement",
"engaging users",
"enhance",
"evidence base",
"external challenge",
"facilitate",
"fast-track",
"flexibilities and freedoms",
"footway",
"framework",
"fulcrum",
"good practice",
"governance",
"guidelines",
"highway",
"holistic",
"improvement levers",
"incentivising",
"income streams",
"funding streams",
"initiative",
"joined up",
"joint working",
"LAAs",
"service users",
"level playing field",
"localities",
"meaningful consultation",
"meaningful dialogue",
"MAAs",
"menu of options",
"multi-agency",
"multidisciplinary",
"outcomes",
"output",
"participatory",
"partnerships",
"pathfinder",
"peer challenge",
"performance network",
"place shaping",
"predictors of beaconicity",
"preventative services",
"priority",
"process driven",
"quick hit",
"quick win",
"resource allocation",
"revenue streams",
"risk based",
"scaled-back",
"scoping",
"seedbed",
"shared priority",
"signpost",
"single point of contact",
"slippage",
"social contracts",
"stakeholder",
"step change",
"strategic",
"overarching",
"streamlined",
"subsidiarity",
"sustainable",
"symposium",
"synergies",
"soundness",
"third sector",
"top-down",
"transparency",
"transformation",
"value-added",
"vision",
"wellbeing",
);
?>
